apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ecotrack-demo
  namespace: argocd
  labels:
    app: ecotrack-demo
    environment: dev
spec:
  project: default
  source:
    repoURL: https://github.com/jmcastellanojimenez/ecotrack-platform.git
    path: applications/demo-app/k8s
    targetRevision: main
  destination:
    server: https://kubernetes.default.svc
    namespace: ecotrack-dev
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
    retry:
      limit: 3
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m